services:
  changelog-bot:
    build: .
    container_name: changelog-bot
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - PORT=80
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CHANGELOG_CHANNEL_ID=${CHANGELOG_CHANNEL_ID}
      - PATCHER_TOKEN=${PATCHER_TOKEN}
      # Optional Wiki variables
      - WIKI_API_URL=${WIKI_API_URL:-}
      - WIKI_API_KEY=${WIKI_API_KEY:-}
      - WIKI_PAGE_ID=${WIKI_PAGE_ID:-}
      # Azure logging configuration
      - PYTHONUNBUFFERED=1
      - WEBSITE_SITE_NAME=THJ-Patcher
      - WEBSITE_HTTPLOGGING_ENABLED=1
      - WEBSITES_PORT=80
    volumes:
      - ./logs:/app/logs
      - .:/app
    networks:
      - changelog-network

networks:
  changelog-network:
    name: changelog-network 