services:
  patcher-api:
    build: .
    container_name: patcher-api
    restart: unless-stopped
    ports:
      - '80:80'
    env_file:
      - .env
    environment:
      - PORT=80
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CHANGELOG_CHANNEL_ID=${CHANGELOG_CHANNEL_ID}
      - PATCHER_TOKEN=${PATCHER_TOKEN}
      - API_BASE_URL=http://patcher-api:80
      # Optional Wiki variables
      - WIKI_API_URL=${WIKI_API_URL:-}
      - WIKI_API_KEY=${WIKI_API_KEY:-}
      - WIKI_PAGE_ID=${WIKI_PAGE_ID:-}
      # Optional Reddit variables
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID:-}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET:-}
      - REDDIT_USERNAME=${REDDIT_USERNAME:-}
      - REDDIT_PASSWORD=${REDDIT_PASSWORD:-}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT:-}
      - REDDIT_SUBREDDIT=${REDDIT_SUBREDDIT:-}
      - REDDIT_FLAIR_NAME=${REDDIT_FLAIR_NAME:-}
    volumes:
      - ./logs:/app/logs
    networks:
      - changelog-network
    command: ['python', 'Patcher_API.py']

  discord-bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CHANGELOG_CHANNEL_ID=${CHANGELOG_CHANNEL_ID}
    volumes:
      - ./logs:/app/logs
    networks:
      - changelog-network
    command: ['python', 'Discord.py']

  reddit-poster:
    build: .
    container_name: reddit-poster
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CHANGELOG_CHANNEL_ID=${CHANGELOG_CHANNEL_ID}
    volumes:
      - ./logs:/app/logs
    networks:
      - changelog-network
    command: ['python', 'reddit_poster.py']

networks:
  changelog-network:
    name: changelog-network
