version: '3.8'

services:
  changelog-bot:
    build: .
    container_name: changelog-bot
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - PORT=80
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CHANGELOG_CHANNEL_ID=${CHANGELOG_CHANNEL_ID}
      - PATCHER_TOKEN=${PATCHER_TOKEN}
      # Optional Wiki variables (feature disabled)
      - WIKI_API_URL=${WIKI_API_URL:-}
      - WIKI_API_KEY=${WIKI_API_KEY:-}
      - WIKI_PAGE_ID=${WIKI_PAGE_ID:-}
      # Enable logging for Azure
      - WEBSITES_ENABLE_APP_SERVICE_STORAGE=true
      - DIAGNOSTICS_AZUREBLOBCONTAINERSASURL=1
      - DIAGNOSTICS_AZUREBLOBRETENTIONINDAYS=7
    volumes:
      - ./logs:/app/logs
      - .:/app
    networks:
      - changelog-network

networks:
  changelog-network:
    name: changelog-network 