services:
  patcher-api:
    build: .
    container_name: patcher-api
    restart: unless-stopped
    ports:
      - '80:80'
    env_file:
      - .env
    environment:
      - PORT=80
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CHANGELOG_CHANNEL_ID=${CHANGELOG_CHANNEL_ID}
      - PATCHER_TOKEN=${PATCHER_TOKEN}
      - API_BASE_URL=http://patcher-api:80
      # Optional Wiki variables
      - WIKI_API_URL=${WIKI_API_URL:-}
      - WIKI_API_KEY=${WIKI_API_KEY:-}
      - WIKI_PAGE_ID=${WIKI_PAGE_ID:-}
    volumes:
      - ./logs:/app/logs
      - .:/app
    networks:
      - changelog-network
    command: ['python', 'Patcher_API.py']

  discord-bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CHANGELOG_CHANNEL_ID=${CHANGELOG_CHANNEL_ID}
    volumes:
      - ./logs:/app/logs
      - .:/app
    networks:
      - changelog-network
    command: ['python', 'Discord.py']

networks:
  changelog-network:
    name: changelog-network
